### ISSUE TITLE
.gitignore usage

### ISSUE THREAD

**Issue by ali92hm** [jmaupin82/Desdemona#1]
- Use `.gitignore` to ignore the bin file and other build files. 
- Also avoid putting data files such as `.text` and `.csv` on git.

**Comment by jmaupin82** [comment]
Thank you for your feedback. I should learn how to use Git more effectively.

**Comment by nmutalik** [comment]
This issue hasn't been properly closed, as it still persists within your code. Please also learn how to use Github more effectively.
